rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "termos-de-uso", to: "policy#terms_of_use"
  get "politica-privacidade", to: "policy#privacy_policy"
  get "thanks", to: "donates#thanks"
  get "show_alerts", to: "alerts#show"
  root to: "donates#index"
  resources :donates do
    get :checkout
    get :consult_payment
    post :checkout
  end

  get "admin", to: "administration#index"
  get "admin/test_alert", to: "administration#send_test_alert"
  get "admin/audio/:file", to: "administration#get_file", as: "audio"
  namespace :admin do
    get "credentials", to: "administration#get_credentials"
  end
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails/app/models/donate.rb
class Donate < ApplicationRecord
end

rails/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails/app/controllers/administration_controller.rb
require "byebug"
require "mp3info"
require "colorize"

class AdministrationController < ApplicationController
  before_action :authenticate_user!

  def index
    @title_page = "Admin"
  end

  def send_test_alert
    id = 33
    system("rm -rf don_audio_#{id}.mp3")

    file_path_audio = "money_soundfx"
    donate = Donate.new(id: id, nickname: "DevCurumin",
                        message: "da nada, o que eu vejo de gente transmitindo the big bang/dois homens e meio aqui na twitch",
                        value: 1023.45)

    params = {
      :name_donate => "donate_#{donate.id}",
      :msg => "#{donate[:message]}",
    }

    TtsService.text_to_speak params

    file_path_msg = "#{params[:name_donate]}"

    audio = gen_audio_donate(file_path_audio, file_path_msg, donate.id)

    puts "vou enviar o alerta de id #{donate.id}".magenta

    SendAlertToViewJob.set(wait: 4.seconds).perform_later(donate.id, donate.nickname, donate.value, donate.message, audio)

    flash.notice = "Alerta será enviado, verifique na rota"

    redirect_to admin_path
  end

  def get_credentials
    @credentials = EfipayService.get_access_token
  end

  def gen_audio_donate(sound_fx, msg_donate, id)
    system("rm -rf public/don_audio_#{id}.mp3")
    system("rm -rf public/tts_donate/donate_*_aux.mp3")

    # system("ffmpeg -i public/#{sound_fx}.mp3 -ar 44100 -ac 2 -ab 128k -f mp3 public/#{sound_fx}_aux.mp3")
    system("ffmpeg -i public/tts_donate/#{msg_donate}.mp3 -ar 44100 -ac 2 -ab 128k -f mp3 public/tts_donate/#{msg_donate}_aux.mp3")

    system("ffmpeg -i \"concat:public/#{sound_fx}_aux.mp3|public/tts_donate/#{msg_donate}_aux.mp3\" -acodec copy public/don_audio_#{id}.mp3")

    system("rm -rf public/tts_donate/#{msg_donate}.mp3")
    system("rm -rf public/tts_donate/#{msg_donate}_aux.mp3")

    return "don_audio_#{id}.mp3"
  end
end

rails/app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :title
  layout "empty"

  def show
  end

  def title
    @title_page = "Alerts"
  end
end

rails/app/controllers/application_controller.rb
require "colorize"

class ApplicationController < ActionController::Base
end

rails/app/controllers/donates_controller.rb
require "rqrcode"

class DonatesController < ApplicationController
  def index
    @title_page = "Donates"
    @donate = Donate.new
  end

  def create
    @donate = Donate.new donate_params
    if @donate.save
      redirect_to donate_checkout_path(@donate)
    else
      redirect_to root_path, flash.alert = "Não deu bom"
    end
  end

  def checkout
    @title_page = "Checkout"
    @donate = Donate.find_by(id: params[:donate_id])
    data = EfipayService.gen_new_payment @donate
    # if data[:code_status] < 300
    qrcode = RQRCode::QRCode.new(data.pix_copia_cola)
    
    @qr_svg = qrcode.as_svg(
      color: "FFF",
      shape_rendering: "crispEdges",
      module_size: 11,
      standalone: true,
      use_path: true,
    )
    # else
    #   redirect_to root_path, alert: "#{data[:message]}"
    # end
  end

  def consult_payment
    @donate = Donate.find_by(id: params[:donate_id])
    @status = EfipayService.consult_payment @donate
  end

  def thanks
    @title_page = "Obrigado!"
  end

  def donate_params
    params.require(:donate).permit(:nickname, :message, :value)
  end
end

rails/app/controllers/policy_controller.rb
class PolicyController < ApplicationController
  def terms_of_use
  end

  def privacy_policy
  end
end

rails/app/helpers/administration_helper.rb
module AdministrationHelper
end

rails/app/helpers/application_helper.rb
require "colorize"

module ApplicationHelper
  # def modals_alerts
  #   shoot_modal("success", flash[:notice]) if flash[:notice]
  #   shoot_modal("error", flash[:alert]) if flash[:alert]
  # end

  # private

  # def shoot_modal(icon, msg)
  #   script = '<script type="text/javascript">'
  #   script += " Swal.fire({ icon: '#{icon}', title: '#{msg}' }) "
  #   script += "</script>"
  #   script.html_safe
  # end
end

rails/app/helpers/donate_helper.rb
module DonateHelper
end

rails/app/helpers/policy_helper.rb
module PolicyHelper
end

rails/app/views/administration/get_credentials.html.erb
<%= @credentials %>

rails/app/views/administration/index.html.erb
<h1>Dashboard</h1>
<a href="<%= admin_test_alert_path %>" class="btn btn-success"
data-turbo="false">
  Testar alerta</a>

rails/app/views/alerts/_alert.html.erb
<div class="alert" id="alert-<%= donate_id %>">
  <p><strong><%= donate_nickname %></strong> fortaleceu com R$<strong><%= donate_value %></strong>.</p>
  <audio id="audio-donate-<%= donate_id %>" preload="auto" autoplay>
    <source src="<%= file_path_audio %>" type="audio/mpeg">
  </audio>
  <style>
  .alert {
    background-color: yellow;
    padding: 20px;
    margin: 20px;
    border: 1px solid #ccc;
  }
  </style>
</div>

rails/app/views/alerts/show.html.erb
<%= turbo_stream_from "alerts" %>

<div id="alert-container">
</div>

rails/app/views/donates/checkout.html.erb
<h1>CHECKOUT</h1>
<% if @qr_svg %>
  <%= raw(@qr_svg.html_safe) %>
<% end %>
<% if @pix_copia_cola %>
  <input class="form-control"
		type="text"
		value="<%= @pix_copia_cola %>" 
		aria-label="copie e cole a chave pix"
	readonly>
<% end %>
<a href="<%= root_path %>"  class="btn btn-success">Já fiz o meu donate!</a>

rails/app/views/donates/consult_payment.html.erb
<h1><%= @status %></h1>

rails/app/views/donates/create.html.erb
<h1>Donate#create</h1>
<p>Find me in app/views/donate/create.html.erb</p>

rails/app/views/donates/index.html.erb
<div class="row">
  <div class="col-8">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title bg-transparent text-center">Mande uma mensagem para @DevCurumin</h1>
        <%= form_with model: @donate do |form| %>
          <div class="form-group">
            <%= form.label :nickname %>
            <%= form.text_field :nickname , class: "form-control", placeholder: "Quem é você?"%>
          </div>
          <div class="form-group">
            <%= form.label :message, "Mensagem" %>
            <%= form.text_area :message , class: "form-control", placeholder: "Sua mensagem para stream"%>
          </div>
          <div class="form-group">
            <%= form.label :value, "Valor" %>
            <%= form.number_field :value , class: "form-control money-input", placeholder: "R$", step: "0.01", min: "0"%>
          </div>
          <%= form.submit "Donate", class: "btn btn-success"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-4">
    <div class="card">
      <div class="card-body ">
        <h4 class="text-center bg-transparent">Top donates</h4>
      </div>
    </div>
  </div>
</div>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Streampix | <%= @title_page %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body data-bs-theme="dark" class="bg-st-dark">
    <%= render 'shared/modals'%>
    <div class="main">
      <%= yield %>
    </div>
    <%#= render 'shared/footer'%>
  </body>
</html>

rails/app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Streampix | <%= @title_page %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

rails/app/views/policy/privacy_policy.html.erb
<h1>Policy#privacy_policy</h1>
<p>Find me in app/views/policy/privacy_policy.html.erb</p>

rails/app/views/policy/terms_of_use.html.erb
<h1>Termos de Uso para o Sistema de Recebimento de Doações para Streams</h1>
<p><strong>Última atualização: 14 de junho de 2024</strong></p>
<p>Bem-vindo ao nosso sistema de recebimento de doações para streams! Ao utilizar nosso serviço, você concorda com os seguintes Termos de Uso. Leia atentamente antes de continuar.</p>
<h2>1. Aceitação dos Termos</h2>
<p>Ao acessar ou utilizar nosso sistema de recebimento de doações ("Serviço"), você concorda em se comprometer com estes Termos de Uso ("Termos"). Se você não concorda com algum destes Termos, não utilize o Serviço.</p>
<h2>2. Descrição do Serviço</h2>
<p>Nosso Serviço permite que os streamers recebam doações de seus espectadores para apoiar suas atividades de streaming. As doações são realizadas através de uma plataforma segura e os fundos são transferidos para a conta do streamer de acordo com os métodos de pagamento disponibilizados.</p>
<h2>3. Elegibilidade</h2>
<p>Para utilizar o Serviço, você deve ser maior de 18 anos ou ter a permissão de um responsável legal. Ao utilizar o Serviço, você declara e garante que cumpre com este requisito de elegibilidade.</p>
<h2>4. Conta de Usuário</h2>
<p>Para acessar o Serviço, você pode ser necessário criar uma conta. Você é responsável por manter a confidencialidade das informações da sua conta e por todas as atividades que ocorram sob sua conta. Notifique-nos imediatamente em caso de qualquer uso não autorizado de sua conta.</p>
<h2>5. Doações</h2>
<ol>
  <li>
    <h3>5.1. Natureza das Doações</h3>
    <p>Todas as doações feitas através do Serviço são consideradas presentes voluntários e não são reembolsáveis. As doações não criam qualquer expectativa de reembolso, serviços, bens ou qualquer outro tipo de contraprestação.</p>
  </li>
  <li>
    <h3>5.2. Processamento de Pagamentos</h3>
    <p>Utilizamos processadores de pagamento de terceiros para facilitar as doações. Ao fazer uma doação, você concorda com os termos e condições dos processadores de pagamento aplicáveis.</p>
  </li>
  <li>
    <h3>5.3. Impostos e Tarifas</h3>
    <p>Você é responsável por quaisquer impostos aplicáveis às doações que você fizer ou receber.</p>
  </li>
</ol>
<h2>6. Uso Aceitável</h2>
<p>Você concorda em usar o Serviço de acordo com todas as leis e regulamentos aplicáveis. Você concorda em não:</p>
<ul>
  <li>Usar o Serviço para qualquer finalidade ilegal ou não autorizada.</li>
  <li>Interferir ou interromper a integridade ou o desempenho do Serviço.</li>
  <li>Tentar obter acesso não autorizado ao Serviço ou às suas redes e sistemas relacionados.</li>
</ul>
<h2>7. Propriedade Intelectual</h2>
<p>Todos os direitos, títulos e interesses no Serviço e seu conteúdo são e permanecerão de propriedade exclusiva da nossa empresa ou de seus licenciadores. Você não pode utilizar qualquer conteúdo do Serviço para qualquer propósito sem a nossa autorização expressa por escrito.</p>
<h2>8. Limitação de Responsabilidade</h2>
<p>Na máxima extensão permitida pela lei aplicável, nossa empresa não será responsável por quaisquer danos diretos, indiretos, incidentais, consequenciais ou punitivos decorrentes de ou relacionados ao uso ou incapacidade de uso do Serviço.</p>
<h2>9. Modificações aos Termos</h2>
<p>Reservamo-nos o direito de modificar estes Termos a qualquer momento. Quaisquer alterações serão publicadas nesta página e a data da última atualização será revisada. Seu uso continuado do Serviço após tais alterações constitui sua aceitação dos novos Termos.</p>
<h2>10. Rescisão</h2>
<p>Podemos rescindir ou suspender seu acesso ao Serviço imediatamente, sem aviso prévio ou responsabilidade, por qualquer motivo, incluindo, sem limitação, se você violar estes Termos. Após a rescisão, seu direito de usar o Serviço cessará imediatamente.</p>
<h2>11. Contato</h2>
<p>Se você tiver qualquer dúvida sobre estes Termos, entre em contato conosco em <a href="[Endereço de E-mail de Contato]">[Endereço de E-mail de Contato]</a>.</p>
<p><strong>Obrigado por usar nosso serviço!</strong></p>

rails/app/views/shared/_footer.html.erb
<footer class="bd-footer py-4 py-md-5 mt-5 bg-body-tertiary">
  <div class="container py-4 py-md-5 px-4 px-md-3 text-body-secondary">
    <div class="row">
      <div class="col-lg-3 mb-3">
        <!--StreamPix logo-->
        <a class="d-inline-flex align-items-center mb-2 text-body-emphasis text-decoration-none" href="/"
          aria-label="Bootstrap">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="d-block me-2" viewBox="0 0 118 94"
            role="img">
            <title>Bootstrap</title>
            <path fill-rule="evenodd" clip-rule="evenodd"
              d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
              fill="currentColor">
            </path>
          </svg>
          <span class="fs-5">Bootstrap</span>
        </a>
        <ul class="list-unstyled small">
          <li class="mb-2">Designed and built with all the love in the world by the <a
              href="/docs/5.3/about/team/">Bootstrap team</a> with the help of <a
              href="https://github.com/twbs/bootstrap/graphs/contributors">our contributors</a>.</li>
          <li class="mb-2">Code licensed <a href="https://github.com/twbs/bootstrap/blob/main/LICENSE" target="_blank"
              rel="license noopener">MIT</a>, docs <a href="https://creativecommons.org/licenses/by/3.0/"
              target="_blank" rel="license noopener">CC BY 3.0</a>.</li>
          <li class="mb-2">Currently v5.3.3.</li>
        </ul>
      </div>
      <div class="col-6 col-lg-2 offset-lg-1 mb-3">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <li class="mb-2"><a href="/">Home</a></li>
          <li class="mb-2"><a href="/docs/5.3/">Docs</a></li>
          <li class="mb-2"><a href="/docs/5.3/examples/">Examples</a></li>
          <li class="mb-2"><a href="https://icons.getbootstrap.com/">Icons</a></li>
          <li class="mb-2"><a href="https://themes.getbootstrap.com/">Themes</a></li>
          <li class="mb-2"><a href="https://blog.getbootstrap.com/">Blog</a></li>
          <li class="mb-2"><a href="https://cottonbureau.com/people/bootstrap" target="_blank" rel="noopener">Swag
              Store</a></li>
        </ul>
      </div>
      <div class="col-6 col-lg-2 mb-3">
        <h5>Projects</h5>
        <ul class="list-unstyled">
          <li class="mb-2"><a href="https://github.com/twbs/bootstrap" target="_blank" rel="noopener">Bootstrap 5</a>
          </li>
          <li class="mb-2"><a href="https://github.com/twbs/bootstrap/tree/v4-dev" target="_blank"
              rel="noopener">Bootstrap 4</a></li>
          <li class="mb-2"><a href="https://github.com/twbs/icons" target="_blank" rel="noopener">Icons</a></li>
          <li class="mb-2"><a href="https://github.com/twbs/rfs" target="_blank" rel="noopener">RFS</a></li>
          <li class="mb-2"><a href="https://github.com/twbs/examples/" target="_blank" rel="noopener">Examples repo</a>
          </li>
        </ul>
      </div>
      <div class="col-6 col-lg-2 mb-3">
        <h5>Community</h5>
        <ul class="list-unstyled">
          <li class="mb-2"><a href="https://github.com/twbs/bootstrap/issues" target="_blank" rel="noopener">Issues</a>
          </li>
          <li class="mb-2"><a href="https://github.com/twbs/bootstrap/discussions" target="_blank"
              rel="noopener">Discussions</a></li>
          <li class="mb-2"><a href="https://github.com/sponsors/twbs" target="_blank" rel="noopener">Corporate
              sponsors</a></li>
          <li class="mb-2"><a href="https://opencollective.com/bootstrap" target="_blank" rel="noopener">Open
              Collective</a></li>
          <li class="mb-2"><a href="https://stackoverflow.com/questions/tagged/bootstrap-5" target="_blank"
              rel="noopener">Stack Overflow</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

rails/app/views/shared/_modals.html.erb
<script type="text/javascript">
<% if notice %>
  Swal.fire({
    icon: 'success',
    title: '<%= notice %>'
  })
<% end %>
<% if alert %>
  Swal.fire({
    icon: 'error',
    title: '<%= alert %>'
  })
<% end %>
</script>

rails/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

rails/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>